version: "3.8"

services:
  metasnap_frontend:
    build: .
    container_name: metasnap_backend
    ports:
      - "4444:3000"
    networks:
      - proxy
    volumes:
      - ./src:/app/src
    restart: always


networks:
  proxy:
    external: true
    name: traefik_proxy
